export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  agentGatewayEnabled: process.env.AGENT_GATEWAY_ENABLED ?? "true",
  agentGatewayProvider: process.env.AGENT_GATEWAY_PROVIDER ?? "legacy",
  agentGatewayModel: process.env.AGENT_GATEWAY_MODEL ?? "",
  hermesEnabled: process.env.HERMES_ENABLED ?? "false",
  hermesModel: process.env.HERMES_MODEL ?? "",
  hermesBaseUrl: process.env.HERMES_BASE_URL ?? "",
  hermesApiKey: process.env.HERMES_API_KEY ?? "",
  hermesTimeoutMs: process.env.HERMES_TIMEOUT_MS ?? "4500",
  hermesRetries: process.env.HERMES_RETRIES ?? "1",
  hermesCircuitFailureThreshold: process.env.HERMES_CIRCUIT_FAILURE_THRESHOLD ?? "3",
  hermesCircuitCooldownMs: process.env.HERMES_CIRCUIT_COOLDOWN_MS ?? "30000",
  n8nEnabled: process.env.N8N_ENABLED ?? "false",
  n8nAllowedWorkflows: process.env.N8N_ALLOWED_WORKFLOWS ?? "",
};
